# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Install Dependencies
    - name: Install Dependencies
      run: sudo apt-get -y install git cmake python-dev build-essential automake autoconf libpng16-16 \
                libpng-dev libpng-tools libjpeg62-dev libexpat1-dev libgtk2.0-dev libopenal-dev \
                libogg-dev libvorbis-dev libgl1-mesa-dev libsdl1.2-dev libavcodec-dev \
                libavcodec-extra libavformat-dev libavresample-dev libavutil-dev libavdevice-dev \
                libpostproc-dev freeglut3-dev libxmu-dev libxi-dev libboost1.67-all-dev

    # Build Vegastrike
    - name: Build Vega Strike
      run: sh/vsbuild.sh
